info:
  app:
    name: trade-order-gateway
    env: prod
    ver: v0.0.1

server:
  port: 8088

actions: http://campus.query1.ksyun.com:8089,http://campus.query2.ksyun.com:8089
meta: http://campus.meta.ksyun.com:8090

spring:
  #  #配置redis
  redis:
    host: 192.168.200.130
    port: 6379
    database: 3
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8  #最大连接数，默认是8
        max-wait: 10000ms #最大连接等待时间，默认是-1 一直等待
        max-idle: 200  #最大空闲连接，高并发的情况下会来回切换连接
        min-idle: 5  #最小空闲连接数，默认是0
